AWSTemplateFormatVersion: '2010-09-09'
Description: 'cm-proxy: unidirectional serverless proxy'

Parameters:
  PermissionsBoundary:
    Type: String

Conditions:
  HavePermissionsBoundary:
    !Not [!Equals [!Ref PermissionsBoundary, "null"]]

Resources:

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /cm-proxy/uni/
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      PermissionsBoundary: !If
        - HavePermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref "AWS::NoValue"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SQSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueUrl
                  - sqs:GetQueueAttributes
                Resource: !GetAtt CMProxyRequestQueue.Arn

  CMProxyRequestQueue:
    Type: AWS::SQS::Queue

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CMProxyFunction
      InvokedViaFunctionUrl: true
      Principal: "*"

  LambdaInvokeFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !Ref CMProxyFunction
      FunctionUrlAuthType: NONE
      Principal: "*"

  CMProxyFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: !Sub |
          import json
          import boto3
          sqs = boto3.client('sqs')

          def handler(event, context):
            res = sqs.send_message(
              QueueUrl="${CMProxyRequestQueue.QueueUrl}",
              MessageBody=json.dumps({"Input": event}),
            )
            return {"statusCode": 200, "body": "{\"status\": \"ok\"}"}

      Handler: index.handler
      Runtime: python3.14
      Architectures: ['arm64']
      Timeout: 30
      Role: !GetAtt LambdaRole.Arn

  CMProxyUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt CMProxyFunction.Arn

Outputs:
  Endpoint:
    Description: 'Public URL of proxy'
    Value: !GetAtt CMProxyUrl.FunctionUrl

  QueueUrl:
    Description: 'Request Queue URL'
    Value: !Ref CMProxyRequestQueue
